// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmcJjiV17BiSp3lT3lUxQOU-VTram6tM',
    appId: '1:186650131497:web:dae7a10470a61e77aab038',
    messagingSenderId: '186650131497',
    projectId: 'fish-farm-app-6a898',
    authDomain: 'fish-farm-app-6a898.firebaseapp.com',
    storageBucket: 'fish-farm-app-6a898.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1ZcgJeyM1CpuV1ehAiRfx_iaASgx-v8',
    appId: '1:186650131497:android:7d9518ee9397eb5caab038',
    messagingSenderId: '186650131497',
    projectId: 'fish-farm-app-6a898',
    storageBucket: 'fish-farm-app-6a898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6DdqEtsFoVjjH5Qur2CEMAGHC8jaqsVc',
    appId: '1:186650131497:ios:3d0192c23a45d7bcaab038',
    messagingSenderId: '186650131497',
    projectId: 'fish-farm-app-6a898',
    storageBucket: 'fish-farm-app-6a898.firebasestorage.app',
    iosBundleId: 'com.example.fishfarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6DdqEtsFoVjjH5Qur2CEMAGHC8jaqsVc',
    appId: '1:186650131497:ios:3d0192c23a45d7bcaab038',
    messagingSenderId: '186650131497',
    projectId: 'fish-farm-app-6a898',
    storageBucket: 'fish-farm-app-6a898.firebasestorage.app',
    iosBundleId: 'com.example.fishfarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpmcJjiV17BiSp3lT3lUxQOU-VTram6tM',
    appId: '1:186650131497:web:d96833375430a397aab038',
    messagingSenderId: '186650131497',
    projectId: 'fish-farm-app-6a898',
    authDomain: 'fish-farm-app-6a898.firebaseapp.com',
    storageBucket: 'fish-farm-app-6a898.firebasestorage.app',
  );

}